plugins:
  eslint:
    enabled: true
    config:
      file: "/frontend/.eslint.js"
      extensions:
        - .vue
        - .js
  csslint:
    enabled: true
  mardownlint:
    enabled: true
  bandit:
    enabled: true
  sonarpython:
    enabled: true
  stylelint:
    enabled: true

exclude_patterns:
  - "**/config/**"
  - "**/dist/**"
  - "**/tests/**"
  - "**/node_modules/**"
