dist: xenial
os: linux
language: node_js
node_js:
  - 12

jobs:
  include:
    - stage: Test
      before_install:
        - cd frontend

      script:
        - npm run eslint:check
        - npm run test
        - npm run build

    - language: python
      python: '3.7'
      before_install:
        - cd backend
      install:
        - pip install -r requirements.txt
      script:
        - coverage run -m pytest
        - coverage report

    - stage: Build + Deploy
      before_install:
        - cd frontend

      script:
        - npm run build
        - cp ../backend/dist/index.html ../backend/dist/static/index.html

      before_deploy:
        - cd ../backend

      deploy:
        provider: heroku
        app: munro-leagues
        api_key: HEROKU_API_KEY
        skip_cleanup: true
        on:
          repo: brownben/munro
          branch: master
