[project]
name = "munro"
version = "2.0.0"
description = "League Results. Sorted."
keywords = ['sports', 'leagues', 'scoring', 'results', 'orienteering']
authors = [
  { name = "Ben Brown", email = "9870007+brownben@users.noreply.github.com" },
]
homepage = 'https://munroleagues.com'
repository = 'https://github.com/brownben/munro'
readme = 'README.md'
license = "MIT"

dependencies = [
  # fastapi
  "fastapi~=0.115.4",
  "uvicorn[standard]~=0.32.0",
  "uvloop~=0.19.0; platform_system != 'Windows'",

  # database
  "piccolo==0.119.0",
  "asyncpg~=0.30.0",

  # results file parsing
  "beautifulsoup4~=4.12.3",
  "lxml~=5.3.0",
  "defusedxml~=0.7.1",

  # check firebase auth tokens
  "google-auth~=2.35.0",
  "requests~=2.32.3",

  "httpx~=0.27.2",    # make requests for results files
  "icalendar~=6.0.1", # generate ical files
]
optional-dependencies.dev = [
  "aiosqlite~=0.20.0",
  "coverage~=7.6.4",
  "mypy~=1.13.0",
  "respx~=0.21.1",
  "ruff~=0.7.1",
  "time-machine~=2.16.0",
  "types-beautifulsoup4~=4.12.0",
  "types-icalendar~=6.0.1",
  "types-requests~=2.32.0",
]

[build-system]
requires = ["setuptools >= 61.0"]
build-backend = "setuptools.build_meta"

[tool.coverage.run]
source = ["src"]

[tool.coverage.report]
omit = [".venv/*", "*/test*", "*/*database_conf.py"]
exclude_lines = ["coverage: ignore"]

[tool.mypy]
strict = true
plugins = "pydantic.mypy"
mypy_path = 'src/types'
files = '**/*.py'
explicit_package_bases = true

[tool.ruff.lint]
ignore = [
  "E501", # Line too long
  "B904", # Raise inside except
]
per-file-ignores = { "./src/database/*" = ["E712"] }

select = [
  "F",    # Pyflakes
  "E",    # pycodestyle (errors)
  "W",    # pycodestyle (warnings)
  "UP",   # pyupgrade
  "B",    # flake8-bugbear
  "SIM",  # flake8-simplify
  "I",    # isort
  "PERF", # Performnce
  "RUF",  # Ruff
]
