[project]
name = "munro"
version = "2.0.0"
description = "League Results. Sorted."
keywords = ['sports', 'leagues', 'scoring', 'results', 'orienteering']
authors = [{ name = "Ben Brown", email = "9870007+brownben@users.noreply.github.com" }]
homepage = 'https://munroleagues.com'
repository = 'https://github.com/brownben/munro'
readme = 'README.md'
license = "MIT"

dependencies = [
  "asyncpg~=0.29.0",
  "defusedxml~=0.7.1",
  "fastapi~=0.110.1",
  "google-auth~=2.29.0",
  "httpx~=0.27.0",
  "icalendar~=5.0.12",
  "piccolo==0.119.0",
  "uvicorn~=0.29.0",
  "requests~=2.31.0"
]
optional-dependencies.dev = [
  "aiosqlite~=0.20.0",
  "coverage~=7.4.4",
  "mypy~=1.9.0",
  "respx~=0.21.1",
  "ruff~=0.3.5",
  "time-machine~=2.14.1",
  "types-icalendar~=5.0.0",
  "types-requests~=2.31.0"
]

[build-system]
requires = ["setuptools >= 61.0"]
build-backend = "setuptools.build_meta"

[tool.coverage.run]
source = ["src"]

[tool.coverage.report]
omit = [".venv/*", "*/test*", "*/*database_conf.py"]
exclude_lines = ["coverage: ignore"]

[tool.mypy]
strict = true
plugins = "pydantic.mypy"
mypy_path = 'src/types'
files = '**/*.py'
explicit_package_bases = true

[tool.ruff.lint]
ignore = [
  "E501", # Line too long
  "B904", # Raise inside except
]
per-file-ignores = { "./src/database/*"=["E712"] }

select = [
  "F",    # Pyflakes
  "E",    # pycodestyle (errors)
  "W",    # pycodestyle (warnings)
  "UP",   # pyupgrade
  "B",    # flake8-bugbear
  "SIM",  # flake8-simplify
  "I",    # isort
  "PERF", # Performnce
  "RUF",  # Ruff
]
