[tool.poetry]
name = "munro"
version = "2.0.0"
description = "League Results. Sorted."
keywords = ['sports', 'leagues', 'scoring', 'results', 'orienteering']
authors = ["Ben Brown <9870007+brownben@users.noreply.github.com>"]
homepage = 'https://munroleagues.com'
repository = 'https://github.com/brownben/munro'
readme = 'README.md'
license = "MIT"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"


[tool.poetry.dependencies]
python = "^3.10"
asyncpg = "^0.29.0"
defusedxml = "^0.7.1"
fastapi = "^0.109.0"
google-auth = "^2.27.0"
httpx = "^0.26.0"
piccolo = "^0.119.0"
uvicorn = "^0.27.0"
requests = "^2.31.0"

[tool.poetry.dev-dependencies]
aiosqlite = "^0.19.0"
coverage = "^7.4.1"
isort = "^5.12.0"
mypy = "^1.7.1"
respx = "^0.20.2"
ruff = "^0.1.15"
time-machine = "^2.13.0"
types-requests = "^2.31.0"


[tool.coverage.run]
source = ["src"]

[tool.coverage.report]
omit = [".venv/*", "*/test*", "*/*database_conf.py"]
exclude_lines = ["coverage: ignore"]

[tool.isort]
profile = "black"

[tool.mypy]
strict = true
plugins = "pydantic.mypy"
mypy_path = 'src/types'
files = '**/*.py'
explicit_package_bases = true

[tool.ruff]
ignore = ["E501"]
per-file-ignores = { "./src/database/*"=["E712"] }
