export const sampleSingleEvent = {
  league: 'Sprintelope',
  results: '',
  id: 'SprintelopeBushEstate2018-05-09',
  routegadget: '',
  website: 'esoc.org.uk',
  winsplits: '',
  organiser: 'ESOC',
  date: '2018-05-09',
  moreInformation: '',
  name: 'Bush Estate',
  resultUploaded: false,
}

export const sampleThreeEvents = [
  {
    'moreInformation': '',
    'results': 'w',
    'organiser': 'Firrhill Boys',
    'name': '200m',
    'league': 'Justice',
    'website': 'wwwwwww',
    'winsplits': 'w',
    'id':
      'Justice200m',
    'resultUploaded': false,
    'date': '',
    'routegadget': 'w',
  },
  {
    'moreInformation': '',
    'results': '',
    'organiser': 'ELO',
    'name': 'Longniddry',
    'league': 'Sprintelope',
    'website': '',
    'winsplits': '',
    'id': 'SprintelopeLongniddry2018-04-18',
    'resultUploaded': false,
    'date': '2018-04-18',
    'routegadget': '',
  },
  {
    'moreInformation': '',
    'results': '',
    'organiser': 'INT',
    'name': 'South Edinburgh',
    'league': 'Sprintelope',
    'website': '',
    'winsplits': '',
    'id': 'SprintelopeSouthEdinburgh2018-04-25',
    'resultUploaded': false,
    'date': '2018-04-25',
    'routegadget': '',
  },
]
