name: CI

on: [push, pull_request]

jobs:
  frontend:
    name: Frontend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend

    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'

      - name: Install Dependencies
        run: npm ci

      - name: Format
        run: npm run format:check

      - name: Format
        run: npm run format:check

      - name: Lint
        run: |
          npm run lint
          npm run prepare

      - name: Typecheck
        run: npm run typecheck

      - name: Test
        run: npm run test

      - name: Run Build
        run: npm run build

  backend:
    name: Backend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: '3.13'

      - name: Install `uv`
        run: curl -LsSf https://astral.sh/uv/install.sh | sh

      - name: Install Dependencies
        run: uv sync --extra dev

      - name: Typecheck
        working-directory: backend
        run: uv run mypy

      - name: Format
        working-directory: backend
        run: |
          uv run ruff format . --check

      - name: Lint
        working-directory: backend
        run: |
          uv run ruff check .

      - name: Test
        working-directory: backend
        run: |
          uv run coverage run -m unittest
          uv run coverage report --skip-empty
