name: Node CI

on: [push]

jobs:
  test:
    name: Test on Node.js 10 and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node_version: [10]
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 10
      uses: actions/setup-node@v1
      with:
        version: 10

    - name: npm install, lint, test and build
      run: |
        cd frontend
        npm install
        npm run lint
        npm test
        npm run build --if-present
