name: CI

on: [push, pull_request]

jobs:
  frontend:
    name: Frontend - Lint + Unit Tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend

    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Dependencies
        run: npm ci

      - name: Lint
        run: npm run check

      - name: Run Build
        run: npm run build

  backend:
    name: Backend - Lint + Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Typecheck
        working-directory: backend
        run: mypy ../backend

      - name: Lint
        working-directory: backend
        run: black . --check --line-length 88

      - name: Test
        working-directory: backend
        run: |
          coverage run -m pytest
          coverage report
